___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

![Image_Assignment](https://i.ibb.co/cY9HhF7/bnote-assignment.gif)

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Assignment 01 (NumPy & Pandas Basics)</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [NUMPY SECTION](#0)
* [PANDAS SECTION](#1)


**In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Section</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### 1. Import NumPy Library.

In [1]:
# YOUR CODE IS HERE

import numpy as np

### 2. Create an array from my_list = [5, 10, 15, 20, 25]

In [2]:
# YOUR CODE IS HERE

# YOUR CODE IS HERE
my_list = np.arange(5, 30, 5)
my_list

array([ 5, 10, 15, 20, 25])

### 3. Generate an array of 5x5 with zeros. 

In [3]:
# YOUR CODE IS HERE

np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 4. Generate an array of 4x4 with ones and assign data type as int.

In [4]:
# YOUR CODE IS HERE
np.ones([4, 4], dtype= int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 5. Make all the values of the array above with the value of 7.

In [5]:
# YOUR CODE IS HERE

arr = np.ones([4, 4], dtype = int)
arr * 7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 6. Create the previous array above by full() method.

In [7]:
# YOUR CODE IS HERE
np.full((4,4), 7)


array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 7. Create an array of even integers from 2 to 16 (inclusive). 

In [8]:
# YOUR CODE IS HERE

np.arange(2, 17, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive).

In [11]:
# YOUR CODE IS HERE

arr = np.arange(0, 25)
#arr
np.array(arr).reshape(5,5)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace method.

In [12]:
# YOUR CODE IS HERE


arr = np.linspace(0, 25, 25, dtype= int)
np.array(arr).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 25]])

### 10. Create randomly 5 numbers with numpy.

In [15]:
# YOUR CODE IS HERE
np.random.rand(5)


array([0.6478612 , 0.30886177, 0.26454443, 0.7864945 , 0.95428427])

### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution.

In [16]:
# YOUR CODE IS HERE

arr = np.random.randn(25)
np.array(arr).reshape(5, 5)

array([[ 0.63768516, -1.46615752, -0.25867316, -1.75784163,  0.61072867],
       [ 0.39720594,  0.37987825, -0.08174636,  0.23278473,  0.73020712],
       [ 0.80464339,  0.2652402 ,  1.97300488,  0.6649575 , -1.1650935 ],
       [-1.35089555,  0.0184891 ,  1.3328108 , -0.9976534 , -0.60715548],
       [ 0.08032044, -0.91583167, -1.03496532, -0.01697815,  1.03950319]])

### 12. Create a 3*4 array of random int numbers between 20 and 50.

In [17]:
# YOUR CODE IS HERE

arr = np.random.randint(20, 50, size = 12)
np.array(arr).reshape(3, 4)


array([[45, 22, 44, 39],
       [28, 20, 20, 23],
       [38, 36, 25, 28]])

### 13. Create an array named "ranarr"consisting of randomly 48 numbers and reshape this array with the shape of 6x8 in different ways.

In [19]:
# YOUR CODE IS HERE

ranarr = np.random.randint(50, size = 48)
np.array(ranarr)
np.array(ranarr).reshape(6, 8)


array([[ 3, 14, 47, 47, 18, 35, 45, 19],
       [ 1, 20, 29, 35, 33, 11, 49,  6],
       [22,  3, 10, 24,  8, 43, 24, 17],
       [30, 11, 43, 41,  1, 39, 48, 37],
       [36, 11,  2,  8, 21, 17, 43,  3],
       [41,  6,  5, 46,  9,  5, 35,  7]])

In [20]:
# YOUR CODE IS HERE (RESHAPING WITH NUM)

np.array(ranarr).reshape(8,6)

array([[ 3, 14, 47, 47, 18, 35],
       [45, 19,  1, 20, 29, 35],
       [33, 11, 49,  6, 22,  3],
       [10, 24,  8, 43, 24, 17],
       [30, 11, 43, 41,  1, 39],
       [48, 37, 36, 11,  2,  8],
       [21, 17, 43,  3, 41,  6],
       [ 5, 46,  9,  5, 35,  7]])

In [ ]:
# YOUR CODE IS HERE (RESHAPING WITH -1)
np.array(ranarr).reshape(3,16)


array([[17, 18,  4, 15,  2, 10,  9,  1,  2,  1, 37, 32, 47, 13, 37, 12],
       [25,  0, 10, 19,  7, 46,  1, 40, 26, 12, 37,  3, 15, 16, 38, 34],
       [23, 27, 38, 35, 15, 25, 30, 39, 34, 44, 24, 10, 32, 23, 24, 35]])

In [ ]:
# YOUR CODE IS HERE (RESHAPING WITH -1)

np.array(ranarr).reshape(12,4)

array([[17, 18,  4, 15],
       [ 2, 10,  9,  1],
       [ 2,  1, 37, 32],
       [47, 13, 37, 12],
       [25,  0, 10, 19],
       [ 7, 46,  1, 40],
       [26, 12, 37,  3],
       [15, 16, 38, 34],
       [23, 27, 38, 35],
       [15, 25, 30, 39],
       [34, 44, 24, 10],
       [32, 23, 24, 35]])

## Numpy Indexing and Selection

### Create an array named "mat" in accordence with the desired output below.

In [24]:
# YOUR CODE IS HERE 
liste = np.arange(1, 17)
mat = np.array(liste).reshape(4, 4)
mat_ = mat
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 14. Using the array above, write a code that reproduces the desired output shown below.<br>

In [25]:
# YOUR CODE IS HERE 
np.array([[6, 7], [10, 11]])

array([[ 6,  7],
       [10, 11]])

### 15. Get the 1st column (index number 0) of the array above.

In [26]:
# YOUR CODE IS HERE 
mat[::, 0]

array([ 1,  5,  9, 13])

### 16. Get the values in 2nd row (index number 1) for every 2 step.

In [ ]:
# YOUR CODE IS HERE 
mat[1, 0:3:2]

array([5, 7])

### 17.Assign 77 to every cell in 3rd column.

In [27]:
# YOUR CODE IS HERE 
for i in mat:
    i[2] = 77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

### 18. (a) Take 2nd row (index number 1) and 1st column (index number 0) , (b) 4th row (index number 3) and 3rd column (index number 2) .

In [28]:
# YOUR CODE IS HERE 
mat[[1, 3], [0, 2]]

array([ 5, 77])

### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [29]:
# YOUR CODE IS HERE 
mat[1::2, 0::2] 

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

### 20. Get the sum of values smaller than 10 and values bigger than 12 in "mat".

In [30]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 

mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [34]:
#THE VALUES SMALLER THAN 10 IN "mat" 



a = mat[mat < 10]
a

array([1, 2, 4, 5, 6, 8, 9])

In [33]:
#THE VALUES BIGGER THAN 12 IN "mat" 


b = mat[mat > 12]
b

array([77, 77, 77, 13, 14, 77, 16])

In [35]:
#  SUM OF THE VALUES SMALLER THAN 10 AND BIGGER THAN 12 IN "mat" 

# YOUR CODE IS HERE 
result = np.add(a, b)
result


array([78, 79, 81, 18, 20, 85, 25])

### 21. Get the standard deviation (std) of the result above.

In [ ]:
# YOUR CODE IS HERE 

np.std(result)

29.700546274093877

### 22. Get the sum of the 2nd column in the original "mat".

In [36]:
# ARRAY OF "mat" 

mat


array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [37]:
# YOUR CODE IS HERE 

np.sum(mat_[::, 1])

32

### 23. Get the median, mean and std of 3rd column in "mat".

In [38]:
#  ARRAY OF "mat" 


mat_

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [43]:
# ASSIGN THE COLUMN WE ARE INTERESTED IN TO A VARIABLE 

# YOUR CODE IS HERE 

var1 = mat_[::, 2].reshape(4, 1)
var1

array([[77],
       [77],
       [77],
       [77]])

In [44]:
# 3RD ROW 

# YOUR CODE IS HERE 

mat_[2]

array([ 9, 10, 77, 12])

In [45]:
# MEDIAN VALUE 
print(np.median(mat_[2]))


11.0


In [46]:
#  MEAN VALUE 



print(np.mean(mat_[2]))


27.0


In [47]:
# STANDART DEVIATION (std) VALUE 

# YOUR CODE IS HERE 


print(np.std(mat_[2]))

28.88771365130858


## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Pandas Section</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Import Pandas Library

In [53]:
import pandas as pd

### Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements.*

In [54]:
# READ Salaries.csv

df = pd.read_csv("Salaries.csv")

In [55]:
# THE FIRST 5 ROWS 
df.head()



Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

     Year  Notes         Agency  Status  
0  2011.0    NaN  San Francisco     NaN  
1  2011.0    NaN  San Francisco     NaN  
2  2011.0    NaN  San Francisco     NaN  
3  2011.0    NaN  San Francisco     NaN  
4  2011.0    NaN  San Francisco     NaN

Desired Output:

![image.png](https://i.ibb.co/6BTmGX8/assignment1a.png)

In [56]:
#  A SAMPLE 

df.sample()

Id      EmployeeName                                      JobTitle  \
26291  26292  PATRICK HENNESSY  APPRENTICE STATIONARY ENGINEER, SEWAGE PLANT   

        BasePay  OvertimePay  OtherPay  Benefits  TotalPay  TotalPayBenefits  \
26291  40600.25        755.0   1666.93       NaN  43022.18          43022.18   

         Year  Notes         Agency  Status  
26291  2011.0    NaN  San Francisco     NaN

Desired Output (WATCH OUT! Your output may NOT be the same as the one):

![image.png](https://i.ibb.co/mcsCxxC/assignment1b.png)

In [57]:
# INFO


df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88822 entries, 0 to 88821
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Id                88822 non-null  int64  
 1   EmployeeName      88822 non-null  object 
 2   JobTitle          88822 non-null  object 
 3   BasePay           88818 non-null  float64
 4   OvertimePay       88821 non-null  float64
 5   OtherPay          88821 non-null  float64
 6   Benefits          52662 non-null  float64
 7   TotalPay          88821 non-null  float64
 8   TotalPayBenefits  88821 non-null  float64
 9   Year              88821 non-null  float64
 10  Notes             0 non-null      float64
 11  Agency            88821 non-null  object 
 12  Status            0 non-null      float64
dtypes: float64(9), int64(1), object(3)
memory usage: 8.8+ MB


In [58]:
# DESCRIPTIVE MEASUREMENTS  

df.describe()


Id        BasePay    OvertimePay       OtherPay  \
count  88822.000000   88818.000000   88821.000000   88821.000000   
mean   44411.500000   72515.868893    5818.335135    4240.788227   
std    25640.847142   43017.639194   12397.195429    8811.236340   
min        1.000000    -166.010000       0.000000   -7058.590000   
25%    22206.250000   45362.300000       0.000000       0.000000   
50%    44411.500000   71179.405000       0.000000    1120.580000   
75%    66616.750000  103037.302500    5930.420000    5207.950000   
max    88822.000000  319275.010000  245131.880000  400184.250000   

           Benefits       TotalPay  TotalPayBenefits          Year  Notes  \
count  52662.000000   88821.000000      88821.000000  88821.000000    0.0   
mean   29417.804224   82572.542973     100014.368736   2011.771867    NaN   
std    14409.903309   51016.788984      62818.276002      0.730772    NaN   
min        0.000000       0.000000          0.000000   2011.000000    NaN   
25%    25827.167500   49109.550000      53838.890000   2011.000000    NaN   
50%    32841.735000   81510.700000      99671.920000   2012.000000    NaN   
75%    37810.562500  115530.000000     140679.180000   2012.000000    NaN   
max    86533.210000  567595.430000     567595.430000   2013.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

Desired Output:

![image.png](https://i.ibb.co/ftMP67H/assignmnet1c.png)

### How many different year values are there?

In [59]:
# YOUR CODE IS HERE 

df.groupby(["Year"]).count()["Id"].sort_values(ascending = False)

Year
2012.0    36766
2011.0    36159
2013.0    15896
Name: Id, dtype: int64

In [60]:
# LET US FIND THE NUMBER OF UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE 
df["Year"].nunique()


3

In [61]:
df

Id       EmployeeName  \
0          1     NATHANIEL FORD   
1          2       GARY JIMENEZ   
2          3     ALBERT PARDINI   
3          4  CHRISTOPHER CHONG   
4          5    PATRICK GARDNER   
...      ...                ...   
88817  88818        Janey  Chan   
88818  88819     Craig S Rigler   
88819  88820      James A Cecil   
88820  88821     Ramona  Torres   
88821  88822        Gary R Farr   

                                             JobTitle    BasePay  OvertimePay  \
0      GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18         0.00   
1                     CAPTAIN III (POLICE DEPARTMENT)  155966.02    245131.88   
2                     CAPTAIN III (POLICE DEPARTMENT)  212739.13    106088.18   
3                WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00     56120.71   
4        DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60      9737.00   
...                                               ...        ...          ...   
88817                                       Asst Engr   81908.53         0.00   
88818                    Sr Fare Collections Receiver   70767.00      5605.01   
88819                            Automotive Machinist   80133.01       333.46   
88820                           Emp & Training Spec 2   79542.07         0.00   
88821                                  Transit Operat        NaN          NaN   

        OtherPay  Benefits   TotalPay  TotalPayBenefits    Year  Notes  \
0      400184.25       NaN  567595.43         567595.43  2011.0    NaN   
1      137811.38       NaN  538909.28         538909.28  2011.0    NaN   
2       16452.60       NaN  335279.91         335279.91  2011.0    NaN   
3      198306.90       NaN  332343.61         332343.61  2011.0    NaN   
4      182234.59       NaN  326373.19         326373.19  2011.0    NaN   
...          ...       ...        ...               ...     ...    ...   
88817       0.00  29686.96   81908.53         111595.49  2013.0    NaN   
88818    6289.10  28933.19   82661.11         111594.30  2013.0    NaN   
88819    1271.35  29849.10   81737.82         111586.92  2013.0    NaN   
88820    2148.00  29887.81   81690.07         111577.88  2013.0    NaN   
88821        NaN       NaN        NaN               NaN     NaN    NaN   

              Agency  Status  
0      San Francisco     NaN  
1      San Francisco     NaN  
2      San Francisco     NaN  
3      San Francisco     NaN  
4      San Francisco     NaN  
...              ...     ...  
88817  San Francisco     NaN  
88818  San Francisco     NaN  
88819  San Francisco     NaN  
88820  San Francisco     NaN  
88821            NaN     NaN  

[88822 rows x 13 columns]

In [62]:
# THE UNIQUE VALUES IN THE COLUMN OF "Year

df["Year"].unique()

array([2011., 2012., 2013.,   nan])

### Print out max and avg values in the column of "Totalpay".

In [63]:
# THE MAXIMUM TOTALPAY


df["TotalPay"].max()   

567595.43

In [64]:
# THE AVERAGE TOTALPAY


df["TotalPay"].mean()

82572.54297339593

### How many records in the TotalPay column are there bigger than avg TotalPay?

In [65]:
# YOUR CODE IS HERE 


df[df["TotalPay"] > df["TotalPay"].mean()]


Id            EmployeeName  \
0          1          NATHANIEL FORD   
1          2            GARY JIMENEZ   
2          3          ALBERT PARDINI   
3          4       CHRISTOPHER CHONG   
4          5         PATRICK GARDNER   
...      ...                     ...   
88805  88806             Henry  Choy   
88807  88808      Patricia M Vicente   
88808  88809  Jaroslaw  Wedrychowski   
88810  88811         Abigail F Maher   
88818  88819          Craig S Rigler   

                                             JobTitle    BasePay  OvertimePay  \
0      GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18         0.00   
1                     CAPTAIN III (POLICE DEPARTMENT)  155966.02    245131.88   
2                     CAPTAIN III (POLICE DEPARTMENT)  212739.13    106088.18   
3                WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00     56120.71   
4        DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60      9737.00   
...                                               ...        ...          ...   
88805                   Airport Operations Supervisor   80589.84      1241.63   
88807                       Senior Eligibility Worker   75033.02      5578.51   
88808                     Forensic Autopsy Technician   73899.00      7162.09   
88810                   Senior Administrative Analyst   92179.03         0.00   
88818                    Sr Fare Collections Receiver   70767.00      5605.01   

        OtherPay  Benefits   TotalPay  TotalPayBenefits    Year  Notes  \
0      400184.25       NaN  567595.43         567595.43  2011.0    NaN   
1      137811.38       NaN  538909.28         538909.28  2011.0    NaN   
2       16452.60       NaN  335279.91         335279.91  2011.0    NaN   
3      198306.90       NaN  332343.61         332343.61  2011.0    NaN   
4      182234.59       NaN  326373.19         326373.19  2011.0    NaN   
...          ...       ...        ...               ...     ...    ...   
88805     983.86  28821.08   82815.33         111636.41  2013.0    NaN   
88807    2048.00  28964.63   82659.53         111624.16  2013.0    NaN   
88808    1863.00  28700.06   82924.09         111624.15  2013.0    NaN   
88810       0.00  19430.74   92179.03         111609.77  2013.0    NaN   
88818    6289.10  28933.19   82661.11         111594.30  2013.0    NaN   

              Agency  Status  
0      San Francisco     NaN  
1      San Francisco     NaN  
2      San Francisco     NaN  
3      San Francisco     NaN  
4      San Francisco     NaN  
...              ...     ...  
88805  San Francisco     NaN  
88807  San Francisco     NaN  
88808  San Francisco     NaN  
88810  San Francisco     NaN  
88818  San Francisco     NaN  

[43648 rows x 13 columns]

Desired Output:

![image.png](https://i.ibb.co/nj84FbZ/assignment1d.png)

In [71]:
# YOUR CODE IS HERE 

#df[df["TotalPay"]>df['TotalPay'].mean()].count("index")["TotalPay"]

df_shape = df[df["TotalPay"] > df["TotalPay"].mean()].shape
df_shape
# row = df_shape[0]
df_shape[0]




43648

### How much does ALBERT PARDINI make money (including benefits)?

In [72]:
# YOUR CODE IS HERE 

df[df["EmployeeName"] == "ALBERT PARDINI"]["TotalPayBenefits"]


2    335279.91
Name: TotalPayBenefits, dtype: float64

### Who is the lowest paid person?

In [73]:
# YOUR CODE IS HERE

df[df["TotalPay"] == df["TotalPay"].min()]["EmployeeName"]

36156        PAULETTE ADAMS
36157         KAUKAB MOHSIN
36158    JOSEPHINE MCCREARY
70877         Roland Baylon
70927      Felecia Phillips
70928       Robert Giannini
70932            Nelly Kuan
70933       William Mathews
70942         Gayle Mathews
70956          Linda Carter
70960         Hui Qin Zhang
70989       Georgina Pineda
70990    Millicent Williams
70991           Richard Lee
70992          Audrey Sylve
70993      Kimberly Johnson
70994        Teddy Querubin
70995         Joann Seabury
70996           David Reyes
70997            Ana Garcia
71077           Heidi Sieck
72797             Vao Davis
72804         Merritt Brown
72829       Refugio Sanchez
72853      Johnnie Benjamin
72876            Victor Pon
72911         Amy Winkelman
72921          John Carajan
Name: EmployeeName, dtype: object

### What are the unique Jobs in dataset?

In [74]:
# YOUR CODE IS HERE 

df["JobTitle"].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ...,
       'Cement Finisher Supervisor 2', 'Payroll Supervisor',
       'Transit Operat'], dtype=object)

### List the top 3 least common Jobs in the dataset.

In [75]:
# YOUR CODE IS HERE 


df["JobTitle"].value_counts().tail(3)

EMPLOYEE ASSISTANCE COUNSELOR    1
POWER GENERATION TECHNICIAN I    1
Transit Operat                   1
Name: JobTitle, dtype: int64

### How many people earned more than avg in 2012?

In [ ]:
# YOUR CODE IS HERE 

len(df[(df["TotalPayBenefits"] > df["TotalPayBenefits"].mean()) & (df["Year"] == 2012)])

20366

### How many people have a title of Manager in their jobs?

In [76]:
# USE APPLY FUNCTION

# YOUR CODE IS HERE 

def job_title(title):
    if "manager" in title.lower():
        return True
    else:
        False

df["JobTitle"].apply(lambda x: job_title(x)).count()

2922

In [ ]:
df

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

### Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe.

In [77]:
# YOUR CODE IS HERE 

sal_new = df.iloc[:,[0, 1, 2, 7, 8]]
df = pd.DataFrame(sal_new)
df

Id       EmployeeName  \
0          1     NATHANIEL FORD   
1          2       GARY JIMENEZ   
2          3     ALBERT PARDINI   
3          4  CHRISTOPHER CHONG   
4          5    PATRICK GARDNER   
...      ...                ...   
88817  88818        Janey  Chan   
88818  88819     Craig S Rigler   
88819  88820      James A Cecil   
88820  88821     Ramona  Torres   
88821  88822        Gary R Farr   

                                             JobTitle   TotalPay  \
0      GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                     CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                     CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4        DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                               ...        ...   
88817                                       Asst Engr   81908.53   
88818                    Sr Fare Collections Receiver   82661.11   
88819                            Automotive Machinist   81737.82   
88820                           Emp & Training Spec 2   81690.07   
88821                                  Transit Operat        NaN   

       TotalPayBenefits  
0             567595.43  
1             538909.28  
2             335279.91  
3             332343.61  
4             326373.19  
...                 ...  
88817         111595.49  
88818         111594.30  
88819         111586.92  
88820         111577.88  
88821               NaN  

[88822 rows x 5 columns]

Desired Output:

![image.png](https://i.ibb.co/ZgFCbPm/assignment1e.png)

### Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df.

In [81]:
# YOUR CODE IS HERE 

sal_new = df.loc[:, "EmployeeName" : "TotalPayBenefits"]
df

EmployeeName                                        JobTitle  \
0         NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1           GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2         ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3      CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4        PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                  ...                                             ...   
88817        Janey  Chan                                       Asst Engr   
88818     Craig S Rigler                    Sr Fare Collections Receiver   
88819      James A Cecil                            Automotive Machinist   
88820     Ramona  Torres                           Emp & Training Spec 2   
88821        Gary R Farr                                  Transit Operat   

        TotalPay  TotalPayBenefits  
0      567595.43         567595.43  
1      538909.28         538909.28  
2      335279.91         335279.91  
3      332343.61         332343.61  
4      326373.19         326373.19  
...          ...               ...  
88817   81908.53         111595.49  
88818   82661.11         111594.30  
88819   81737.82         111586.92  
88820   81690.07         111577.88  
88821        NaN               NaN  

[88822 rows x 4 columns]

Desired Output:

![image.png](https://i.ibb.co/s2CYS7H/assignment1f.png)

### Print out the names of the employees who earn more than min but less than avg.

In [79]:
# YOUR CODE IS HERE 
df[(df["TotalPayBenefits"] > df["TotalPayBenefits"].min()) & (df["TotalPayBenefits"] < df["TotalPayBenefits"].mean())][["EmployeeName","TotalPayBenefits"]]


EmployeeName  TotalPayBenefits
9524       ERIKA KIEFER          99983.35
9525     GREGORY DORAIS          99982.16
9526     GRACE ENRIQUEZ          99962.70
9527     RONALD SHEREDY          99961.59
9528       MARY GODFREY          99961.33
...                 ...               ...
72920  Charles Williams             16.65
72921      John Carajan             12.90
72922       John Draper              5.17
72923      Cherise Wong              4.16
72924      Donald Clark              1.91

[44555 rows x 2 columns]

Desired Output:

![image.png](https://i.ibb.co/mtNB2TX/assignment1g.png)

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

________